// main.go - Code generator: exports ModeRules presets from backend game package.
// Generates mcpserver/internal/semantic/mode_rules_gen.go.
// Usage: go run ./cmd/codegen (from backend/ directory)
package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"

	"github.com/darkforest/backend/internal/game"
)

func main() {
	classic := game.ClassicModePresetExport()
	relics := game.RelicsModePresetExport()

	finalCode, err := format.Source([]byte(fmt.Sprintf(codeTemplate,
		classic.Mode, classic.LightspeedUsage, classic.LightspeedCombinedActionCost,
		classic.LightspeedDeployCost, classic.LightspeedJumpCost,
		classic.LightspeedCarryCap, classic.LightspeedMessageEnabled,
		classic.RelicDistributionEnabled, classic.StrikeOrigin,
		classic.StrikeMissBehavior, classic.StrikeCanDestroyRelic,
		classic.TurnTimeoutSeconds, classic.Description,
		relics.Mode, relics.LightspeedUsage, relics.LightspeedCombinedActionCost,
		relics.LightspeedDeployCost, relics.LightspeedJumpCost,
		relics.LightspeedCarryCap, relics.LightspeedMessageEnabled,
		relics.RelicDistributionEnabled, relics.StrikeOrigin,
		relics.StrikeMissBehavior, relics.StrikeCanDestroyRelic,
		relics.TurnTimeoutSeconds, relics.Description,
	)))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format source failed: %v\n", err)
		os.Exit(1)
	}

	outPath := filepath.Join("..", "mcpserver", "internal", "semantic", "mode_rules_gen.go")
	if err := os.WriteFile(outPath, finalCode, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "writing generated file failed: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("generated:", outPath)
}

const codeTemplate = "// Code generated - DO NOT EDIT.\n// Generated by backend/cmd/codegen.\n\npackage semantic\n\nvar classicModeRules = ModeRules{\n\tMode: %q,\n\tLightspeedUsage: %q,\n\tLightspeedCombinedActionCost: %d,\n\tLightspeedDeployCost: %d,\n\tLightspeedJumpCost: %d,\n\tLightspeedCarryCap: %d,\n\tLightspeedMessageEnabled: %v,\n\tRelicDistributionEnabled: %v,\n\tStrikeOrigin: %q,\n\tStrikeMissBehavior: %q,\n\tStrikeCanDestroyRelic: %v,\n\tTurnTimeoutSeconds: %d,\n\tDescription: %q,\n}\n\nvar relicsModeRules = ModeRules{\n\tMode: %q,\n\tLightspeedUsage: %q,\n\tLightspeedCombinedActionCost: %d,\n\tLightspeedDeployCost: %d,\n\tLightspeedJumpCost: %d,\n\tLightspeedCarryCap: %d,\n\tLightspeedMessageEnabled: %v,\n\tRelicDistributionEnabled: %v,\n\tStrikeOrigin: %q,\n\tStrikeMissBehavior: %q,\n\tStrikeCanDestroyRelic: %v,\n\tTurnTimeoutSeconds: %d,\n\tDescription: %q,\n}\n"
