// main.go - Code generator: exports ModeRules presets from backend game package.
// Generates mcpserver/internal/semantic/mode_rules_gen.go.
// Usage: go run ./cmd/codegen (from backend/ directory)
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/darkforest/backend/internal/game"
)

func main() {
	classic := game.ClassicModePresetExport()
	relics := game.RelicsModePresetExport()

	genCode := fmt.Sprintf(codeTemplate,
		classic.Mode, classic.LightspeedUsage, classic.LightspeedCombinedActionCost,
		classic.LightspeedCombinedActionCostSpecified, classic.LightspeedDeployCost,
		classic.LightspeedJumpCostRandom, classic.LightspeedJumpCostSpecified,
		classic.LightspeedCarryCap, classic.LightspeedMessageEnabled,
		classic.RelicDistributionEnabled, classic.StrikeOrigin,
		classic.StrikeMissBehavior, classic.StrikeCanDestroyRelic, classic.Description,
		relics.Mode, relics.LightspeedUsage, relics.LightspeedCombinedActionCost,
		relics.LightspeedCombinedActionCostSpecified, relics.LightspeedDeployCost,
		relics.LightspeedJumpCostRandom, relics.LightspeedJumpCostSpecified,
		relics.LightspeedCarryCap, relics.LightspeedMessageEnabled,
		relics.RelicDistributionEnabled, relics.StrikeOrigin,
		relics.StrikeMissBehavior, relics.StrikeCanDestroyRelic, relics.Description,
	)

	outPath := filepath.Join("..", "mcpserver", "internal", "semantic", "mode_rules_gen.go")
	if err := os.WriteFile(outPath, []byte(genCode), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "writing generated file failed: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("generated:", outPath)
}

const codeTemplate = "// Code generated - DO NOT EDIT.\n// Generated by backend/cmd/codegen.\n\npackage semantic\n\nvar classicModeRules = ModeRules{\n\tMode: %q,\n\tLightspeedUsage: %q,\n\tLightspeedCombinedActionCost: %d,\n\tLightspeedCombinedActionCostSpecified: %d,\n\tLightspeedDeployCost: %d,\n\tLightspeedJumpCostRandom: %d,\n\tLightspeedJumpCostSpecified: %d,\n\tLightspeedCarryCap: %d,\n\tLightspeedMessageEnabled: %v,\n\tRelicDistributionEnabled: %v,\n\tStrikeOrigin: %q,\n\tStrikeMissBehavior: %q,\n\tStrikeCanDestroyRelic: %v,\n\tDescription: %q,\n}\n\nvar relicsModeRules = ModeRules{\n\tMode: %q,\n\tLightspeedUsage: %q,\n\tLightspeedCombinedActionCost: %d,\n\tLightspeedCombinedActionCostSpecified: %d,\n\tLightspeedDeployCost: %d,\n\tLightspeedJumpCostRandom: %d,\n\tLightspeedJumpCostSpecified: %d,\n\tLightspeedCarryCap: %d,\n\tLightspeedMessageEnabled: %v,\n\tRelicDistributionEnabled: %v,\n\tStrikeOrigin: %q,\n\tStrikeMissBehavior: %q,\n\tStrikeCanDestroyRelic: %v,\n\tDescription: %q,\n}\n"
