// Code generated - DO NOT EDIT.
// Generated by backend/cmd/codegen.

package semantic

var classicModeRules = ModeRules{
	Mode: "classic",
	LightspeedUsage: "oneTime",
	LightspeedCombinedActionCost: 10,
	LightspeedCombinedActionCostSpecified: 13,
	LightspeedDeployCost: 0,
	LightspeedJumpCostRandom: 0,
	LightspeedJumpCostSpecified: 0,
	LightspeedCarryCap: 0,
	LightspeedMessageEnabled: false,
	RelicDistributionEnabled: false,
	StrikeOrigin: "direct",
	StrikeMissBehavior: "discard",
	StrikeCanDestroyRelic: false,
	Description: "快速直接的星际博弈，打击即刻判定，光速飞船一次性使用",
}

var relicsModeRules = ModeRules{
	Mode: "civilization_relics",
	LightspeedUsage: "reusable",
	LightspeedCombinedActionCost: 0,
	LightspeedCombinedActionCostSpecified: 0,
	LightspeedDeployCost: 10,
	LightspeedJumpCostRandom: 3,
	LightspeedJumpCostSpecified: 5,
	LightspeedCarryCap: 5,
	LightspeedMessageEnabled: true,
	RelicDistributionEnabled: true,
	StrikeOrigin: "ownerPlanet",
	StrikeMissBehavior: "discard",
	StrikeCanDestroyRelic: true,
	Description: "打击经飞行抵达，星系间散布远古文明遗迹，光速飞船可复用并支持留言",
}
