package game

var CardDefinitions []CardDef = []CardDef{
	{
		ID:          "broadcast_star_cooperation",
		Name:        "恒星广播",
		Type:        CardTypeBroadcast,
		Energy:      0,
		Quantity:    9,
		Description: "向距离 1 以内的星系发送广播信号，若对方回应且双方均选择合作，各获得 3 能量",
		Extended: map[string]interface{}{
			"subtype": "cooperation",
			"range":   1,
		},
	},
	{
		ID:          "broadcast_star_disguise",
		Name:        "恒星广播",
		Type:        CardTypeBroadcast,
		Energy:      0,
		Quantity:    5,
		Description: "向距离 1 以内的星系发送广播信号，伪装方可获得 5 能量（若对方合作）",
		Extended: map[string]interface{}{
			"subtype": "disguise",
			"range":   1,
		},
	},
	{
		ID:          "broadcast_cosmic_cooperation",
		Name:        "宇宙广播",
		Type:        CardTypeBroadcast,
		Energy:      1,
		Quantity:    6,
		Description: "向距离 2 以内的星系发送广播信号，若对方回应且双方均选择合作，各获得 3 能量",
		Extended: map[string]interface{}{
			"subtype": "cooperation",
			"range":   2,
		},
	},
	{
		ID:          "broadcast_cosmic_disguise",
		Name:        "宇宙广播",
		Type:        CardTypeBroadcast,
		Energy:      1,
		Quantity:    4,
		Description: "向距离 2 以内的星系发送广播信号，伪装方可获得 5 能量（若对方合作）",
		Extended: map[string]interface{}{
			"subtype": "disguise",
			"range":   2,
		},
	},
	{
		ID:          "broadcast_ultra_cooperation",
		Name:        "超距广播",
		Type:        CardTypeBroadcast,
		Energy:      2,
		Quantity:    2,
		Description: "无视距离发送广播信号，若对方回应且双方均选择合作，各获得 3 能量",
		Extended: map[string]interface{}{
			"subtype": "cooperation",
			"range":   1000,
		},
	},
	{
		ID:          "broadcast_ultra_disguise",
		Name:        "超距广播",
		Type:        CardTypeBroadcast,
		Energy:      2,
		Quantity:    2,
		Description: "无视距离发送广播信号，伪装方可获得 5 能量（若对方合作）",
		Extended: map[string]interface{}{
			"subtype": "disguise",
			"range":   1000,
		},
	},
	{
		ID:          "strike_thermal",
		Name:        "热核打击",
		Type:        CardTypeStrike,
		Energy:      4,
		Quantity:    4,
		Description: "打击无特殊效果，可被掩体星环防御",
		Extended: map[string]interface{}{
			"level": 1,
			"speed": 1,
		},
	},
	{
		ID:          "strike_light_particle",
		Name:        "光粒打击",
		Type:        CardTypeStrike,
		Energy:      6,
		Quantity:    4,
		Description: "无论是否被防御，均毁灭目标星系恒星",
		Extended: map[string]interface{}{
			"level": 2,
			"speed": 1,
		},
	},
	{
		ID:          "strike_annihilation",
		Name:        "湮灭打击",
		Type:        CardTypeStrike,
		Energy:      8,
		Quantity:    3,
		Description: "无论是否被防御，均毁灭目标星系恒星及所有建设牌",
		Extended: map[string]interface{}{
			"level": 3,
			"speed": 1,
		},
	},
	{
		ID:          "strike_dimensional",
		Name:        "降维打击",
		Type:        CardTypeStrike,
		Energy:      10,
		Quantity:    3,
		Description: "彻底清除目标星系",
		Extended: map[string]interface{}{
			"level": 4,
			"speed": 1,
		},
	},
	{
		ID:          "strike_tech_lock",
		Name:        "科技锁死",
		Type:        CardTypeStrike,
		Energy:      4,
		Quantity:    3,
		Description: "无视防御，打击生效时，目标玩家立即弃掉全部手牌",
		Extended: map[string]interface{}{
			"level":  4,
			"speed":  1,
			"effect": "discard_hand",
		},
	},
	{
		ID:          "defense_shield_ring",
		Name:        "掩体星环",
		Type:        CardTypeDefense,
		Energy:      6,
		Quantity:    5,
		Description: "可在等级 2 及以下的打击中幸存，可防御热核打击、但不免除光粒打击的效果",
		Extended: map[string]interface{}{
			"protection_level": 2,
			"duration":         "permanent",
		},
	},
	{
		ID:          "defense_quantum_ghost",
		Name:        "量子幽灵",
		Type:        CardTypeDefense,
		Energy:      8,
		Quantity:    3,
		Description: "进入量子幽灵态，可在等级 3 及以下的打击中幸存",
		Extended: map[string]interface{}{
			"protection_level": 3,
			"duration":         "permanent",
		},
	},
	{
		ID:          "facility_solar_array",
		Name:        "太阳能阵列",
		Type:        CardTypeFacility,
		Energy:      2,
		Quantity:    5,
		Description: "每回合开始时获得 1 点能量产出，依赖恒星",
		Extended: map[string]interface{}{
			"energy_per_turn": 1,
			"duration":        "permanent",
		},
	},
	{
		ID:          "facility_fusion_reactor",
		Name:        "聚变反应堆",
		Type:        CardTypeFacility,
		Energy:      3,
		Quantity:    4,
		Description: "每回合获得 1 点能量产出，不依赖恒星",
		Extended: map[string]interface{}{
			"energy_per_turn": 1,
			"duration":        "permanent",
		},
	},
	{
		ID:          "facility_antimatter_engine",
		Name:        "反物质引擎",
		Type:        CardTypeFacility,
		Energy:      6,
		Quantity:    3,
		Description: "每回合获得 2 点能量产出，不依赖恒星",
		Extended: map[string]interface{}{
			"energy_per_turn": 2,
			"duration":        "permanent",
		},
	},
	{
		ID:          "facility_dyson_sphere",
		Name:        "戴森球",
		Type:        CardTypeFacility,
		Energy:      6,
		Quantity:    3,
		Description: "每回合获得 3 点能量产出，依赖恒星，每个星系只能建造1个",
		Extended: map[string]interface{}{
			"energy_per_turn": 3,
			"duration":        "permanent",
		},
	},
	{
		ID:          "facility_monitoring_station",
		Name:        "监听基地",
		Type:        CardTypeFacility,
		Energy:      2,
		Quantity:    2,
		Description: "所在星系接收广播后可不做回应",
		Extended: map[string]interface{}{
			"ability":  "detect_broadcast",
			"duration": "permanent",
		},
	},
	{
		ID:          "facility_lightspeed_ship",
		Name:        "光速飞船",
		Type:        CardTypeFacility,
		Energy:      10,
		Quantity:    2,
		Description: "可重复使用。跃迁模式二选一：随机（3能量，不公开位置）或指定（5能量，公开位置）。可携带0-5点能量至新星球，余下能量选择遗留（供继承）或销毁。可填写≤10字符留言（额外1能量），继承者私有揭示可见。",
		Extended: map[string]interface{}{
			"ability":  "escape",
			"duration": "permanent",
		},
	},
}

const TotalCards = 72
