// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_match_queues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomMatchQueue = `-- name: CreateCustomMatchQueue :one
INSERT INTO custom_match_queues (id, queue_id, queue_name, creator_id, min_players, max_players, status, base_game_mode, custom_rules)
VALUES (uuid_generate_v4(), $1, $2, $3, $4, $5, 'waiting', $6, $7)
RETURNING id
`

type CreateCustomMatchQueueParams struct {
	QueueID     string
	QueueName   string
	CreatorID   pgtype.UUID
	MinPlayers  int32
	MaxPlayers  int32
	BaseGameMode string
	CustomRules []byte
}

func (q *Queries) CreateCustomMatchQueue(ctx context.Context, arg CreateCustomMatchQueueParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createCustomMatchQueue,
		arg.QueueID,
		arg.QueueName,
		arg.CreatorID,
		arg.MinPlayers,
		arg.MaxPlayers,
		arg.BaseGameMode,
		arg.CustomRules,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getCustomMatchQueueByQueueID = `-- name: GetCustomMatchQueueByQueueID :one
SELECT id, queue_id, queue_name, creator_id, max_players, min_players, status, created_at, updated_at, base_game_mode, custom_rules
FROM custom_match_queues
WHERE queue_id = $1
`

func (q *Queries) GetCustomMatchQueueByQueueID(ctx context.Context, queueID string) (CustomMatchQueue, error) {
	row := q.db.QueryRow(ctx, getCustomMatchQueueByQueueID, queueID)
	var i CustomMatchQueue
	err := row.Scan(
		&i.ID,
		&i.QueueID,
		&i.QueueName,
		&i.CreatorID,
		&i.MaxPlayers,
		&i.MinPlayers,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseGameMode,
		&i.CustomRules,
	)
	return i, err
}

const getCustomMatchQueuePlayers = `-- name: GetCustomMatchQueuePlayers :many
SELECT cmp.id, cmp.queue_id, cmp.player_id, cmp.joined_at, cmp.is_ready, p.display_name
FROM custom_match_queue_players cmp
JOIN players p ON p.id = cmp.player_id
WHERE cmp.queue_id = $1
ORDER BY cmp.joined_at ASC
`

type GetCustomMatchQueuePlayersRow struct {
	ID          pgtype.UUID
	QueueID     pgtype.UUID
	PlayerID    pgtype.UUID
	JoinedAt    pgtype.Timestamptz
	IsReady     bool
	DisplayName string
}

func (q *Queries) GetCustomMatchQueuePlayers(ctx context.Context, queueID pgtype.UUID) ([]GetCustomMatchQueuePlayersRow, error) {
	rows, err := q.db.Query(ctx, getCustomMatchQueuePlayers, queueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustomMatchQueuePlayersRow{}
	for rows.Next() {
		var i GetCustomMatchQueuePlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.QueueID,
			&i.PlayerID,
			&i.JoinedAt,
			&i.IsReady,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const addPlayerToCustomQueue = `-- name: AddPlayerToCustomQueue :exec
INSERT INTO custom_match_queue_players (id, queue_id, player_id, is_ready)
VALUES (uuid_generate_v4(), $1, $2, true)
ON CONFLICT (queue_id, player_id) DO NOTHING
`

type AddPlayerToCustomQueueParams struct {
	QueueID  pgtype.UUID
	PlayerID pgtype.UUID
}

func (q *Queries) AddPlayerToCustomQueue(ctx context.Context, arg AddPlayerToCustomQueueParams) error {
	_, err := q.db.Exec(ctx, addPlayerToCustomQueue, arg.QueueID, arg.PlayerID)
	return err
}

const removePlayerFromCustomQueue = `-- name: RemovePlayerFromCustomQueue :exec
DELETE FROM custom_match_queue_players
WHERE queue_id = $1 AND player_id = $2
`

type RemovePlayerFromCustomQueueParams struct {
	QueueID  pgtype.UUID
	PlayerID pgtype.UUID
}

func (q *Queries) RemovePlayerFromCustomQueue(ctx context.Context, arg RemovePlayerFromCustomQueueParams) error {
	_, err := q.db.Exec(ctx, removePlayerFromCustomQueue, arg.QueueID, arg.PlayerID)
	return err
}

const playerInCustomQueue = `-- name: PlayerInCustomQueue :one
SELECT EXISTS(
	SELECT 1 FROM custom_match_queue_players
	WHERE queue_id = $1 AND player_id = $2
)
`

type PlayerInCustomQueueParams struct {
	QueueID  pgtype.UUID
	PlayerID pgtype.UUID
}

func (q *Queries) PlayerInCustomQueue(ctx context.Context, arg PlayerInCustomQueueParams) (bool, error) {
	row := q.db.QueryRow(ctx, playerInCustomQueue, arg.QueueID, arg.PlayerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateCustomQueueStatus = `-- name: UpdateCustomQueueStatus :exec
UPDATE custom_match_queues
SET status = $2
WHERE id = $1
`

type UpdateCustomQueueStatusParams struct {
	QueueID pgtype.UUID
	Status  string
}

func (q *Queries) UpdateCustomQueueStatus(ctx context.Context, arg UpdateCustomQueueStatusParams) error {
	_, err := q.db.Exec(ctx, updateCustomQueueStatus, arg.QueueID, arg.Status)
	return err
}

const deleteEmptyCustomQueue = `-- name: DeleteEmptyCustomQueue :exec
DELETE FROM custom_match_queues
WHERE id = $1
AND NOT EXISTS (SELECT 1 FROM custom_match_queue_players WHERE queue_id = $1)
`

func (q *Queries) DeleteEmptyCustomQueue(ctx context.Context, queueID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmptyCustomQueue, queueID)
	return err
}

const getPlayerCustomQueues = `-- name: GetPlayerCustomQueues :many
SELECT cmq.queue_id, cmq.queue_name, cmq.min_players, cmq.max_players, cmq.status
FROM custom_match_queues cmq
JOIN custom_match_queue_players cmpq ON cmpq.queue_id = cmq.id
WHERE cmpq.player_id = $1
`

type GetPlayerCustomQueuesRow struct {
	QueueID    string
	QueueName  string
	MinPlayers int32
	MaxPlayers int32
	Status     string
}

func (q *Queries) GetPlayerCustomQueues(ctx context.Context, playerID pgtype.UUID) ([]GetPlayerCustomQueuesRow, error) {
	rows, err := q.db.Query(ctx, getPlayerCustomQueues, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerCustomQueuesRow{}
	for rows.Next() {
		var i GetPlayerCustomQueuesRow
		if err := rows.Scan(
			&i.QueueID,
			&i.QueueName,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
