// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: custom_match_queues.sql

package db

import (
	"context"
)

const addPlayerToCustomQueue = `-- name: AddPlayerToCustomQueue :exec
INSERT INTO custom_match_queue_players (id, queue_id, player_id, is_ready)
VALUES (?1, ?2, ?3, true)
ON CONFLICT (queue_id, player_id) DO NOTHING
`

type AddPlayerToCustomQueueParams struct {
	ID       string `json:"id"`
	QueueID  string `json:"queue_id"`
	PlayerID string `json:"player_id"`
}

func (q *Queries) AddPlayerToCustomQueue(ctx context.Context, arg AddPlayerToCustomQueueParams) error {
	_, err := q.db.ExecContext(ctx, addPlayerToCustomQueue, arg.ID, arg.QueueID, arg.PlayerID)
	return err
}

const countWaitingRoomsByMapID = `-- name: CountWaitingRoomsByMapID :one
SELECT COUNT(*) FROM custom_match_queues
WHERE map_id = ?1 AND status = 'waiting'
`

// Count waiting custom rooms referencing a given map.
// Used by DELETE /api/maps/{id} to block deletion while a waiting room references the map.
func (q *Queries) CountWaitingRoomsByMapID(ctx context.Context, mapID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWaitingRoomsByMapID, mapID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomMatchQueue = `-- name: CreateCustomMatchQueue :one

INSERT INTO custom_match_queues (id, queue_id, queue_name, creator_id, min_players, max_players, status, base_game_mode, custom_rules, map_id)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, 'waiting', ?7, ?8, ?9)
RETURNING id
`

type CreateCustomMatchQueueParams struct {
	ID           string  `json:"id"`
	QueueID      string  `json:"queue_id"`
	QueueName    string  `json:"queue_name"`
	CreatorID    string  `json:"creator_id"`
	MinPlayers   int64   `json:"min_players"`
	MaxPlayers   int64   `json:"max_players"`
	BaseGameMode string  `json:"base_game_mode"`
	CustomRules  *string `json:"custom_rules"`
	MapID        *string `json:"map_id"`
}

// Custom Match Queue queries (SQLite dialect)
// Original plpgsql functions inlined as plain sqlc queries; id generated in app layer (google/uuid).
func (q *Queries) CreateCustomMatchQueue(ctx context.Context, arg CreateCustomMatchQueueParams) (string, error) {
	row := q.db.QueryRowContext(ctx, createCustomMatchQueue,
		arg.ID,
		arg.QueueID,
		arg.QueueName,
		arg.CreatorID,
		arg.MinPlayers,
		arg.MaxPlayers,
		arg.BaseGameMode,
		arg.CustomRules,
		arg.MapID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteEmptyCustomQueue = `-- name: DeleteEmptyCustomQueue :exec
DELETE FROM custom_match_queues
WHERE custom_match_queues.id = ?1
AND NOT EXISTS (SELECT 1 FROM custom_match_queue_players WHERE custom_match_queue_players.queue_id = custom_match_queues.id)
`

func (q *Queries) DeleteEmptyCustomQueue(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEmptyCustomQueue, id)
	return err
}

const getCustomMatchQueueByQueueID = `-- name: GetCustomMatchQueueByQueueID :one
SELECT id, queue_id, queue_name, creator_id, max_players, min_players, status, created_at, updated_at, base_game_mode, custom_rules, map_id
FROM custom_match_queues
WHERE queue_id = ?1
`

type GetCustomMatchQueueByQueueIDRow struct {
	ID           string  `json:"id"`
	QueueID      string  `json:"queue_id"`
	QueueName    string  `json:"queue_name"`
	CreatorID    string  `json:"creator_id"`
	MaxPlayers   int64   `json:"max_players"`
	MinPlayers   int64   `json:"min_players"`
	Status       string  `json:"status"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	BaseGameMode string  `json:"base_game_mode"`
	CustomRules  *string `json:"custom_rules"`
	MapID        *string `json:"map_id"`
}

func (q *Queries) GetCustomMatchQueueByQueueID(ctx context.Context, queueID string) (GetCustomMatchQueueByQueueIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomMatchQueueByQueueID, queueID)
	var i GetCustomMatchQueueByQueueIDRow
	err := row.Scan(
		&i.ID,
		&i.QueueID,
		&i.QueueName,
		&i.CreatorID,
		&i.MaxPlayers,
		&i.MinPlayers,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaseGameMode,
		&i.CustomRules,
		&i.MapID,
	)
	return i, err
}

const getCustomMatchQueuePlayers = `-- name: GetCustomMatchQueuePlayers :many
SELECT cmp.id, cmp.queue_id, cmp.player_id, cmp.joined_at, cmp.is_ready, p.display_name
FROM custom_match_queue_players cmp
JOIN players p ON p.id = cmp.player_id
WHERE cmp.queue_id = ?1
ORDER BY cmp.joined_at ASC
`

type GetCustomMatchQueuePlayersRow struct {
	ID          string `json:"id"`
	QueueID     string `json:"queue_id"`
	PlayerID    string `json:"player_id"`
	JoinedAt    string `json:"joined_at"`
	IsReady     bool   `json:"is_ready"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) GetCustomMatchQueuePlayers(ctx context.Context, queueID string) ([]GetCustomMatchQueuePlayersRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomMatchQueuePlayers, queueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCustomMatchQueuePlayersRow{}
	for rows.Next() {
		var i GetCustomMatchQueuePlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.QueueID,
			&i.PlayerID,
			&i.JoinedAt,
			&i.IsReady,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerCustomQueues = `-- name: GetPlayerCustomQueues :many
SELECT cmq.queue_id, cmq.queue_name, cmq.min_players, cmq.max_players, cmq.status
FROM custom_match_queues cmq
JOIN custom_match_queue_players cmpq ON cmpq.queue_id = cmq.id
WHERE cmpq.player_id = ?1
`

type GetPlayerCustomQueuesRow struct {
	QueueID    string `json:"queue_id"`
	QueueName  string `json:"queue_name"`
	MinPlayers int64  `json:"min_players"`
	MaxPlayers int64  `json:"max_players"`
	Status     string `json:"status"`
}

func (q *Queries) GetPlayerCustomQueues(ctx context.Context, playerID string) ([]GetPlayerCustomQueuesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPlayerCustomQueues, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerCustomQueuesRow{}
	for rows.Next() {
		var i GetPlayerCustomQueuesRow
		if err := rows.Scan(
			&i.QueueID,
			&i.QueueName,
			&i.MinPlayers,
			&i.MaxPlayers,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const playerInCustomQueue = `-- name: PlayerInCustomQueue :one
SELECT EXISTS(
	SELECT 1 FROM custom_match_queue_players
	WHERE queue_id = ?1 AND player_id = ?2
)
`

type PlayerInCustomQueueParams struct {
	QueueID  string `json:"queue_id"`
	PlayerID string `json:"player_id"`
}

func (q *Queries) PlayerInCustomQueue(ctx context.Context, arg PlayerInCustomQueueParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, playerInCustomQueue, arg.QueueID, arg.PlayerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removePlayerFromCustomQueue = `-- name: RemovePlayerFromCustomQueue :exec
DELETE FROM custom_match_queue_players
WHERE queue_id = ?1 AND player_id = ?2
`

type RemovePlayerFromCustomQueueParams struct {
	QueueID  string `json:"queue_id"`
	PlayerID string `json:"player_id"`
}

func (q *Queries) RemovePlayerFromCustomQueue(ctx context.Context, arg RemovePlayerFromCustomQueueParams) error {
	_, err := q.db.ExecContext(ctx, removePlayerFromCustomQueue, arg.QueueID, arg.PlayerID)
	return err
}

const updateCustomQueueStatus = `-- name: UpdateCustomQueueStatus :exec
UPDATE custom_match_queues
SET status = ?2, updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
`

type UpdateCustomQueueStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateCustomQueueStatus(ctx context.Context, arg UpdateCustomQueueStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomQueueStatus, arg.ID, arg.Status)
	return err
}
