// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maps.sql

package db

import (
	"context"
)

const countUserMaps = `-- name: CountUserMaps :one
SELECT COUNT(*)
FROM maps
WHERE created_by = ?1 AND is_official = false
`

// Quota check for the P3 upload endpoint: max 10 personal maps per user (is_official=false)
func (q *Queries) CountUserMaps(ctx context.Context, createdBy *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserMaps, createdBy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMap = `-- name: CreateMap :one
INSERT INTO maps (id, slug, name, description, is_official, created_by, version, layout_json)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)
RETURNING id, slug, name, description, is_official, created_by, version, layout_json, created_at, updated_at
`

type CreateMapParams struct {
	ID          string  `json:"id"`
	Slug        *string `json:"slug"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsOfficial  bool    `json:"is_official"`
	CreatedBy   *string `json:"created_by"`
	Version     int64   `json:"version"`
	LayoutJson  string  `json:"layout_json"`
}

func (q *Queries) CreateMap(ctx context.Context, arg CreateMapParams) (Map, error) {
	row := q.db.QueryRowContext(ctx, createMap,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.IsOfficial,
		arg.CreatedBy,
		arg.Version,
		arg.LayoutJson,
	)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsOfficial,
		&i.CreatedBy,
		&i.Version,
		&i.LayoutJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMap = `-- name: DeleteMap :exec
DELETE FROM maps
WHERE id = ?1
`

func (q *Queries) DeleteMap(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMap, id)
	return err
}

const getMapByID = `-- name: GetMapByID :one
SELECT id, slug, name, description, is_official, created_by, version, layout_json, created_at, updated_at
FROM maps
WHERE id = ?1 LIMIT 1
`

func (q *Queries) GetMapByID(ctx context.Context, id string) (Map, error) {
	row := q.db.QueryRowContext(ctx, getMapByID, id)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsOfficial,
		&i.CreatedBy,
		&i.Version,
		&i.LayoutJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMapBySlug = `-- name: GetMapBySlug :one
SELECT id, slug, name, description, is_official, created_by, version, layout_json, created_at, updated_at
FROM maps
WHERE slug = ?1 LIMIT 1
`

func (q *Queries) GetMapBySlug(ctx context.Context, slug *string) (Map, error) {
	row := q.db.QueryRowContext(ctx, getMapBySlug, slug)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsOfficial,
		&i.CreatedBy,
		&i.Version,
		&i.LayoutJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllMaps = `-- name: ListAllMaps :many
SELECT id, slug, name, description, is_official, created_by, version, layout_json, created_at, updated_at
FROM maps
ORDER BY created_at DESC
LIMIT ?1 OFFSET ?2
`

type ListAllMapsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListAllMaps(ctx context.Context, arg ListAllMapsParams) ([]Map, error) {
	rows, err := q.db.QueryContext(ctx, listAllMaps, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Map{}
	for rows.Next() {
		var i Map
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IsOfficial,
			&i.CreatedBy,
			&i.Version,
			&i.LayoutJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMapsByOwner = `-- name: ListMapsByOwner :many
SELECT id, slug, name, description, is_official, created_by, version, layout_json, created_at, updated_at
FROM maps
WHERE created_by = ?1 AND is_official = false
ORDER BY updated_at DESC
`

// Editor "my maps" panel: personal maps uploaded by the current user (is_official=false)
func (q *Queries) ListMapsByOwner(ctx context.Context, createdBy *string) ([]Map, error) {
	rows, err := q.db.QueryContext(ctx, listMapsByOwner, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Map{}
	for rows.Next() {
		var i Map
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IsOfficial,
			&i.CreatedBy,
			&i.Version,
			&i.LayoutJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfficialMaps = `-- name: ListOfficialMaps :many
SELECT id, slug, name, description, is_official, created_by, version, layout_json, created_at, updated_at
FROM maps
WHERE is_official = true
ORDER BY created_at ASC
`

func (q *Queries) ListOfficialMaps(ctx context.Context) ([]Map, error) {
	rows, err := q.db.QueryContext(ctx, listOfficialMaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Map{}
	for rows.Next() {
		var i Map
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.IsOfficial,
			&i.CreatedBy,
			&i.Version,
			&i.LayoutJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMap = `-- name: UpdateMap :one
UPDATE maps
SET name = ?2, description = ?3, layout_json = ?4, version = version + 1, updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
RETURNING id, slug, name, description, is_official, created_by, version, layout_json, created_at, updated_at
`

type UpdateMapParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	LayoutJson  string  `json:"layout_json"`
}

func (q *Queries) UpdateMap(ctx context.Context, arg UpdateMapParams) (Map, error) {
	row := q.db.QueryRowContext(ctx, updateMap,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.LayoutJson,
	)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.IsOfficial,
		&i.CreatedBy,
		&i.Version,
		&i.LayoutJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
