// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (id, room_code, host_id, status, player_count, ai_count)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, room_code, host_id, status, player_count, ai_count, created_at, updated_at
`

type CreateMatchParams struct {
	ID          pgtype.UUID `json:"id"`
	RoomCode    string      `json:"room_code"`
	HostID      pgtype.UUID `json:"host_id"`
	Status      string      `json:"status"`
	PlayerCount int32       `json:"player_count"`
	AiCount     int32       `json:"ai_count"`
}

type CreateMatchRow struct {
	ID          pgtype.UUID        `json:"id"`
	RoomCode    string             `json:"room_code"`
	HostID      pgtype.UUID        `json:"host_id"`
	Status      string             `json:"status"`
	PlayerCount int32              `json:"player_count"`
	AiCount     int32              `json:"ai_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (CreateMatchRow, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.ID,
		arg.RoomCode,
		arg.HostID,
		arg.Status,
		arg.PlayerCount,
		arg.AiCount,
	)
	var i CreateMatchRow
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.HostID,
		&i.Status,
		&i.PlayerCount,
		&i.AiCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMatch = `-- name: DeleteMatch :exec
DELETE FROM matches
WHERE id = $1
`

func (q *Queries) DeleteMatch(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMatch, id)
	return err
}

const finishMatch = `-- name: FinishMatch :one
UPDATE matches
SET status = 'finished', finished_at = CURRENT_TIMESTAMP, winner_id = $2, winner_type = $3, total_turns = $4, duration = $5, game_log = $6, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, status, finished_at, winner_id, winner_type, total_turns, duration, updated_at
`

type FinishMatchParams struct {
	ID         pgtype.UUID `json:"id"`
	WinnerID   pgtype.UUID `json:"winner_id"`
	WinnerType *string     `json:"winner_type"`
	TotalTurns int32       `json:"total_turns"`
	Duration   int32       `json:"duration"`
	GameLog    *string     `json:"game_log"`
}

type FinishMatchRow struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	WinnerID   pgtype.UUID        `json:"winner_id"`
	WinnerType *string            `json:"winner_type"`
	TotalTurns int32              `json:"total_turns"`
	Duration   int32              `json:"duration"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) FinishMatch(ctx context.Context, arg FinishMatchParams) (FinishMatchRow, error) {
	row := q.db.QueryRow(ctx, finishMatch,
		arg.ID,
		arg.WinnerID,
		arg.WinnerType,
		arg.TotalTurns,
		arg.Duration,
		arg.GameLog,
	)
	var i FinishMatchRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.FinishedAt,
		&i.WinnerID,
		&i.WinnerType,
		&i.TotalTurns,
		&i.Duration,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, room_code, host_id, status, player_count, ai_count, winner_id, winner_type, total_turns, duration, started_at, finished_at, created_at, updated_at
FROM matches
WHERE id = $1 LIMIT 1
`

type GetMatchByIDRow struct {
	ID          pgtype.UUID        `json:"id"`
	RoomCode    string             `json:"room_code"`
	HostID      pgtype.UUID        `json:"host_id"`
	Status      string             `json:"status"`
	PlayerCount int32              `json:"player_count"`
	AiCount     int32              `json:"ai_count"`
	WinnerID    pgtype.UUID        `json:"winner_id"`
	WinnerType  *string            `json:"winner_type"`
	TotalTurns  int32              `json:"total_turns"`
	Duration    int32              `json:"duration"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMatchByID(ctx context.Context, id pgtype.UUID) (GetMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i GetMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.HostID,
		&i.Status,
		&i.PlayerCount,
		&i.AiCount,
		&i.WinnerID,
		&i.WinnerType,
		&i.TotalTurns,
		&i.Duration,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMatchByRoomCode = `-- name: GetMatchByRoomCode :one
SELECT id, room_code, host_id, status, player_count, ai_count, winner_id, winner_type, total_turns, duration, started_at, finished_at, created_at, updated_at
FROM matches
WHERE room_code = $1 LIMIT 1
`

type GetMatchByRoomCodeRow struct {
	ID          pgtype.UUID        `json:"id"`
	RoomCode    string             `json:"room_code"`
	HostID      pgtype.UUID        `json:"host_id"`
	Status      string             `json:"status"`
	PlayerCount int32              `json:"player_count"`
	AiCount     int32              `json:"ai_count"`
	WinnerID    pgtype.UUID        `json:"winner_id"`
	WinnerType  *string            `json:"winner_type"`
	TotalTurns  int32              `json:"total_turns"`
	Duration    int32              `json:"duration"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMatchByRoomCode(ctx context.Context, roomCode string) (GetMatchByRoomCodeRow, error) {
	row := q.db.QueryRow(ctx, getMatchByRoomCode, roomCode)
	var i GetMatchByRoomCodeRow
	err := row.Scan(
		&i.ID,
		&i.RoomCode,
		&i.HostID,
		&i.Status,
		&i.PlayerCount,
		&i.AiCount,
		&i.WinnerID,
		&i.WinnerType,
		&i.TotalTurns,
		&i.Duration,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMatches = `-- name: ListMatches :many
SELECT id, room_code, host_id, status, player_count, ai_count, winner_id, winner_type, total_turns, duration, started_at, finished_at, created_at, updated_at
FROM matches
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMatchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListMatchesRow struct {
	ID          pgtype.UUID        `json:"id"`
	RoomCode    string             `json:"room_code"`
	HostID      pgtype.UUID        `json:"host_id"`
	Status      string             `json:"status"`
	PlayerCount int32              `json:"player_count"`
	AiCount     int32              `json:"ai_count"`
	WinnerID    pgtype.UUID        `json:"winner_id"`
	WinnerType  *string            `json:"winner_type"`
	TotalTurns  int32              `json:"total_turns"`
	Duration    int32              `json:"duration"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMatches(ctx context.Context, arg ListMatchesParams) ([]ListMatchesRow, error) {
	rows, err := q.db.Query(ctx, listMatches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchesRow{}
	for rows.Next() {
		var i ListMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomCode,
			&i.HostID,
			&i.Status,
			&i.PlayerCount,
			&i.AiCount,
			&i.WinnerID,
			&i.WinnerType,
			&i.TotalTurns,
			&i.Duration,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByPlayer = `-- name: ListMatchesByPlayer :many
SELECT m.id, m.room_code, m.host_id, m.status, m.player_count, m.ai_count, m.winner_id, m.winner_type, m.total_turns, m.duration, m.started_at, m.finished_at, m.created_at, m.updated_at
FROM matches m
JOIN match_players mp ON m.id = mp.match_id
WHERE mp.player_id = $1
ORDER BY m.created_at DESC
LIMIT $2 OFFSET $3
`

type ListMatchesByPlayerParams struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type ListMatchesByPlayerRow struct {
	ID          pgtype.UUID        `json:"id"`
	RoomCode    string             `json:"room_code"`
	HostID      pgtype.UUID        `json:"host_id"`
	Status      string             `json:"status"`
	PlayerCount int32              `json:"player_count"`
	AiCount     int32              `json:"ai_count"`
	WinnerID    pgtype.UUID        `json:"winner_id"`
	WinnerType  *string            `json:"winner_type"`
	TotalTurns  int32              `json:"total_turns"`
	Duration    int32              `json:"duration"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMatchesByPlayer(ctx context.Context, arg ListMatchesByPlayerParams) ([]ListMatchesByPlayerRow, error) {
	rows, err := q.db.Query(ctx, listMatchesByPlayer, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMatchesByPlayerRow{}
	for rows.Next() {
		var i ListMatchesByPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomCode,
			&i.HostID,
			&i.Status,
			&i.PlayerCount,
			&i.AiCount,
			&i.WinnerID,
			&i.WinnerType,
			&i.TotalTurns,
			&i.Duration,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startMatch = `-- name: StartMatch :one
UPDATE matches
SET status = 'playing', started_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, status, started_at, updated_at
`

type StartMatchRow struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) StartMatch(ctx context.Context, id pgtype.UUID) (StartMatchRow, error) {
	row := q.db.QueryRow(ctx, startMatch, id)
	var i StartMatchRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.StartedAt,
		&i.UpdatedAt,
	)
	return i, err
}
