// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match_players.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlayerToMatch = `-- name: AddPlayerToMatch :one
INSERT INTO match_players (id, match_id, player_id, player_number, is_host, position, is_eliminated, energy, destroyed_stars, broadcast_count, strike_count)
VALUES ($1, $2, $3, $4, $5, $6, FALSE, 3, 0, 0, 0)
RETURNING id, match_id, player_id, player_number, is_host, position, is_eliminated, energy, destroyed_stars, broadcast_count, strike_count, created_at
`

type AddPlayerToMatchParams struct {
	ID           pgtype.UUID `json:"id"`
	MatchID      pgtype.UUID `json:"match_id"`
	PlayerID     pgtype.UUID `json:"player_id"`
	PlayerNumber int32       `json:"player_number"`
	IsHost       bool        `json:"is_host"`
	Position     int32       `json:"position"`
}

type AddPlayerToMatchRow struct {
	ID             pgtype.UUID        `json:"id"`
	MatchID        pgtype.UUID        `json:"match_id"`
	PlayerID       pgtype.UUID        `json:"player_id"`
	PlayerNumber   int32              `json:"player_number"`
	IsHost         bool               `json:"is_host"`
	Position       int32              `json:"position"`
	IsEliminated   bool               `json:"is_eliminated"`
	Energy         int32              `json:"energy"`
	DestroyedStars int32              `json:"destroyed_stars"`
	BroadcastCount int32              `json:"broadcast_count"`
	StrikeCount    int32              `json:"strike_count"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) AddPlayerToMatch(ctx context.Context, arg AddPlayerToMatchParams) (AddPlayerToMatchRow, error) {
	row := q.db.QueryRow(ctx, addPlayerToMatch,
		arg.ID,
		arg.MatchID,
		arg.PlayerID,
		arg.PlayerNumber,
		arg.IsHost,
		arg.Position,
	)
	var i AddPlayerToMatchRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerID,
		&i.PlayerNumber,
		&i.IsHost,
		&i.Position,
		&i.IsEliminated,
		&i.Energy,
		&i.DestroyedStars,
		&i.BroadcastCount,
		&i.StrikeCount,
		&i.CreatedAt,
	)
	return i, err
}

const countPlayersInMatch = `-- name: CountPlayersInMatch :one
SELECT COUNT(*)
FROM match_players
WHERE match_id = $1
`

func (q *Queries) CountPlayersInMatch(ctx context.Context, matchID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayersInMatch, matchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMatchPlayer = `-- name: GetMatchPlayer :one
SELECT id, match_id, player_id, player_number, is_host, position, final_rank, is_eliminated, eliminated_turn, energy, destroyed_stars, broadcast_count, strike_count, created_at
FROM match_players
WHERE match_id = $1 AND player_id = $2 LIMIT 1
`

type GetMatchPlayerParams struct {
	MatchID  pgtype.UUID `json:"match_id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

func (q *Queries) GetMatchPlayer(ctx context.Context, arg GetMatchPlayerParams) (MatchPlayer, error) {
	row := q.db.QueryRow(ctx, getMatchPlayer, arg.MatchID, arg.PlayerID)
	var i MatchPlayer
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerID,
		&i.PlayerNumber,
		&i.IsHost,
		&i.Position,
		&i.FinalRank,
		&i.IsEliminated,
		&i.EliminatedTurn,
		&i.Energy,
		&i.DestroyedStars,
		&i.BroadcastCount,
		&i.StrikeCount,
		&i.CreatedAt,
	)
	return i, err
}

const listPlayersByMatch = `-- name: ListPlayersByMatch :many
SELECT id, match_id, player_id, player_number, is_host, position, final_rank, is_eliminated, eliminated_turn, energy, destroyed_stars, broadcast_count, strike_count, created_at
FROM match_players
WHERE match_id = $1
ORDER BY player_number ASC
`

func (q *Queries) ListPlayersByMatch(ctx context.Context, matchID pgtype.UUID) ([]MatchPlayer, error) {
	rows, err := q.db.Query(ctx, listPlayersByMatch, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchPlayer{}
	for rows.Next() {
		var i MatchPlayer
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerID,
			&i.PlayerNumber,
			&i.IsHost,
			&i.Position,
			&i.FinalRank,
			&i.IsEliminated,
			&i.EliminatedTurn,
			&i.Energy,
			&i.DestroyedStars,
			&i.BroadcastCount,
			&i.StrikeCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePlayerFromMatch = `-- name: RemovePlayerFromMatch :exec
DELETE FROM match_players
WHERE match_id = $1 AND player_id = $2
`

type RemovePlayerFromMatchParams struct {
	MatchID  pgtype.UUID `json:"match_id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

func (q *Queries) RemovePlayerFromMatch(ctx context.Context, arg RemovePlayerFromMatchParams) error {
	_, err := q.db.Exec(ctx, removePlayerFromMatch, arg.MatchID, arg.PlayerID)
	return err
}

const updateMatchPlayerStats = `-- name: UpdateMatchPlayerStats :one
UPDATE match_players
SET final_rank = $2, is_eliminated = $3, eliminated_turn = $4, energy = $5, destroyed_stars = $6, broadcast_count = $7, strike_count = $8
WHERE match_id = $1 AND player_id = $9
RETURNING match_id, player_id, final_rank, is_eliminated, eliminated_turn, energy, destroyed_stars, broadcast_count, strike_count
`

type UpdateMatchPlayerStatsParams struct {
	MatchID        pgtype.UUID `json:"match_id"`
	FinalRank      *int32      `json:"final_rank"`
	IsEliminated   bool        `json:"is_eliminated"`
	EliminatedTurn *int32      `json:"eliminated_turn"`
	Energy         int32       `json:"energy"`
	DestroyedStars int32       `json:"destroyed_stars"`
	BroadcastCount int32       `json:"broadcast_count"`
	StrikeCount    int32       `json:"strike_count"`
	PlayerID       pgtype.UUID `json:"player_id"`
}

type UpdateMatchPlayerStatsRow struct {
	MatchID        pgtype.UUID `json:"match_id"`
	PlayerID       pgtype.UUID `json:"player_id"`
	FinalRank      *int32      `json:"final_rank"`
	IsEliminated   bool        `json:"is_eliminated"`
	EliminatedTurn *int32      `json:"eliminated_turn"`
	Energy         int32       `json:"energy"`
	DestroyedStars int32       `json:"destroyed_stars"`
	BroadcastCount int32       `json:"broadcast_count"`
	StrikeCount    int32       `json:"strike_count"`
}

func (q *Queries) UpdateMatchPlayerStats(ctx context.Context, arg UpdateMatchPlayerStatsParams) (UpdateMatchPlayerStatsRow, error) {
	row := q.db.QueryRow(ctx, updateMatchPlayerStats,
		arg.MatchID,
		arg.FinalRank,
		arg.IsEliminated,
		arg.EliminatedTurn,
		arg.Energy,
		arg.DestroyedStars,
		arg.BroadcastCount,
		arg.StrikeCount,
		arg.PlayerID,
	)
	var i UpdateMatchPlayerStatsRow
	err := row.Scan(
		&i.MatchID,
		&i.PlayerID,
		&i.FinalRank,
		&i.IsEliminated,
		&i.EliminatedTurn,
		&i.Energy,
		&i.DestroyedStars,
		&i.BroadcastCount,
		&i.StrikeCount,
	)
	return i, err
}
