// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matchmaking_queues.sql

package db

import (
	"context"
	"strings"
)

const clearMatchmakingQueue = `-- name: ClearMatchmakingQueue :exec
DELETE FROM matchmaking_queues
WHERE player_id IN (/*SLICE:player_ids*/?)
`

func (q *Queries) ClearMatchmakingQueue(ctx context.Context, playerIds []string) error {
	query := clearMatchmakingQueue
	var queryParams []interface{}
	if len(playerIds) > 0 {
		for _, v := range playerIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:player_ids*/?", strings.Repeat(",?", len(playerIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:player_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const countPlayersInQueue = `-- name: CountPlayersInQueue :one
SELECT COUNT(*)
FROM matchmaking_queues
WHERE preferred_count = ?1
`

func (q *Queries) CountPlayersInQueue(ctx context.Context, preferredCount int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayersInQueue, preferredCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllQueues = `-- name: GetAllQueues :many
SELECT id, player_id, preferred_count, joined_at, timeout
FROM matchmaking_queues
ORDER BY joined_at ASC
`

func (q *Queries) GetAllQueues(ctx context.Context) ([]MatchmakingQueue, error) {
	rows, err := q.db.QueryContext(ctx, getAllQueues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchmakingQueue{}
	for rows.Next() {
		var i MatchmakingQueue
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.PreferredCount,
			&i.JoinedAt,
			&i.Timeout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerInQueue = `-- name: GetPlayerInQueue :one
SELECT id, player_id, preferred_count, joined_at, timeout
FROM matchmaking_queues
WHERE player_id = ?1 LIMIT 1
`

func (q *Queries) GetPlayerInQueue(ctx context.Context, playerID string) (MatchmakingQueue, error) {
	row := q.db.QueryRowContext(ctx, getPlayerInQueue, playerID)
	var i MatchmakingQueue
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.PreferredCount,
		&i.JoinedAt,
		&i.Timeout,
	)
	return i, err
}

const getPlayersInQueue = `-- name: GetPlayersInQueue :many
SELECT id, player_id, preferred_count, joined_at, timeout
FROM matchmaking_queues
WHERE preferred_count = ?1
ORDER BY joined_at ASC
LIMIT ?2
`

type GetPlayersInQueueParams struct {
	PreferredCount int64 `json:"preferred_count"`
	Limit          int64 `json:"limit"`
}

func (q *Queries) GetPlayersInQueue(ctx context.Context, arg GetPlayersInQueueParams) ([]MatchmakingQueue, error) {
	rows, err := q.db.QueryContext(ctx, getPlayersInQueue, arg.PreferredCount, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchmakingQueue{}
	for rows.Next() {
		var i MatchmakingQueue
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.PreferredCount,
			&i.JoinedAt,
			&i.Timeout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinMatchmakingQueue = `-- name: JoinMatchmakingQueue :one
INSERT INTO matchmaking_queues (id, player_id, preferred_count, timeout)
VALUES (?1, ?2, ?3, ?4)
ON CONFLICT (player_id) DO UPDATE
SET preferred_count = excluded.preferred_count, timeout = excluded.timeout, joined_at = CURRENT_TIMESTAMP
RETURNING id, player_id, preferred_count, joined_at, timeout
`

type JoinMatchmakingQueueParams struct {
	ID             string `json:"id"`
	PlayerID       string `json:"player_id"`
	PreferredCount int64  `json:"preferred_count"`
	Timeout        int64  `json:"timeout"`
}

func (q *Queries) JoinMatchmakingQueue(ctx context.Context, arg JoinMatchmakingQueueParams) (MatchmakingQueue, error) {
	row := q.db.QueryRowContext(ctx, joinMatchmakingQueue,
		arg.ID,
		arg.PlayerID,
		arg.PreferredCount,
		arg.Timeout,
	)
	var i MatchmakingQueue
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.PreferredCount,
		&i.JoinedAt,
		&i.Timeout,
	)
	return i, err
}

const leaveMatchmakingQueue = `-- name: LeaveMatchmakingQueue :exec
DELETE FROM matchmaking_queues
WHERE player_id = ?1
`

func (q *Queries) LeaveMatchmakingQueue(ctx context.Context, playerID string) error {
	_, err := q.db.ExecContext(ctx, leaveMatchmakingQueue, playerID)
	return err
}
