// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matchmaking_queues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearMatchmakingQueue = `-- name: ClearMatchmakingQueue :exec
DELETE FROM matchmaking_queues
WHERE player_id = ANY($1::uuid[])
`

func (q *Queries) ClearMatchmakingQueue(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearMatchmakingQueue, dollar_1)
	return err
}

const countPlayersInQueue = `-- name: CountPlayersInQueue :one
SELECT COUNT(*)
FROM matchmaking_queues
WHERE preferred_count = $1
`

func (q *Queries) CountPlayersInQueue(ctx context.Context, preferredCount int32) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayersInQueue, preferredCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllQueues = `-- name: GetAllQueues :many
SELECT id, player_id, preferred_count, joined_at, timeout
FROM matchmaking_queues
ORDER BY joined_at ASC
`

func (q *Queries) GetAllQueues(ctx context.Context) ([]MatchmakingQueue, error) {
	rows, err := q.db.Query(ctx, getAllQueues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchmakingQueue{}
	for rows.Next() {
		var i MatchmakingQueue
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.PreferredCount,
			&i.JoinedAt,
			&i.Timeout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerInQueue = `-- name: GetPlayerInQueue :one
SELECT id, player_id, preferred_count, joined_at, timeout
FROM matchmaking_queues
WHERE player_id = $1 LIMIT 1
`

func (q *Queries) GetPlayerInQueue(ctx context.Context, playerID pgtype.UUID) (MatchmakingQueue, error) {
	row := q.db.QueryRow(ctx, getPlayerInQueue, playerID)
	var i MatchmakingQueue
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.PreferredCount,
		&i.JoinedAt,
		&i.Timeout,
	)
	return i, err
}

const getPlayersInQueue = `-- name: GetPlayersInQueue :many
SELECT id, player_id, preferred_count, joined_at, timeout
FROM matchmaking_queues
WHERE preferred_count = $1
ORDER BY joined_at ASC
LIMIT $2
`

type GetPlayersInQueueParams struct {
	PreferredCount int32 `json:"preferred_count"`
	Limit          int32 `json:"limit"`
}

func (q *Queries) GetPlayersInQueue(ctx context.Context, arg GetPlayersInQueueParams) ([]MatchmakingQueue, error) {
	rows, err := q.db.Query(ctx, getPlayersInQueue, arg.PreferredCount, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchmakingQueue{}
	for rows.Next() {
		var i MatchmakingQueue
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.PreferredCount,
			&i.JoinedAt,
			&i.Timeout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const joinMatchmakingQueue = `-- name: JoinMatchmakingQueue :one
INSERT INTO matchmaking_queues (id, player_id, preferred_count, timeout)
VALUES ($1, $2, $3, $4)
ON CONFLICT (player_id) DO UPDATE
SET preferred_count = EXCLUDED.preferred_count, timeout = EXCLUDED.timeout, joined_at = CURRENT_TIMESTAMP
RETURNING id, player_id, preferred_count, joined_at, timeout
`

type JoinMatchmakingQueueParams struct {
	ID             pgtype.UUID `json:"id"`
	PlayerID       pgtype.UUID `json:"player_id"`
	PreferredCount int32       `json:"preferred_count"`
	Timeout        int32       `json:"timeout"`
}

func (q *Queries) JoinMatchmakingQueue(ctx context.Context, arg JoinMatchmakingQueueParams) (MatchmakingQueue, error) {
	row := q.db.QueryRow(ctx, joinMatchmakingQueue,
		arg.ID,
		arg.PlayerID,
		arg.PreferredCount,
		arg.Timeout,
	)
	var i MatchmakingQueue
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.PreferredCount,
		&i.JoinedAt,
		&i.Timeout,
	)
	return i, err
}

const leaveMatchmakingQueue = `-- name: LeaveMatchmakingQueue :exec
DELETE FROM matchmaking_queues
WHERE player_id = $1
`

func (q *Queries) LeaveMatchmakingQueue(ctx context.Context, playerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, leaveMatchmakingQueue, playerID)
	return err
}
