// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 自定义匹配队列表
type CustomMatchQueue struct {
	ID        pgtype.UUID `json:"id"`
	QueueID   string      `json:"queue_id"`
	QueueName string      `json:"queue_name"`
	CreatorID pgtype.UUID `json:"creator_id"`
	// 最大玩家数（3-5）
	MaxPlayers int32 `json:"max_players"`
	// 最小玩家数（3-5）
	MinPlayers int32 `json:"min_players"`
	// 队列状态：waiting, matching, full, started
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 自定义匹配队列玩家关联表
type CustomMatchQueuePlayer struct {
	ID       pgtype.UUID        `json:"id"`
	QueueID  pgtype.UUID        `json:"queue_id"`
	PlayerID pgtype.UUID        `json:"player_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
	IsReady  bool               `json:"is_ready"`
}

// 邀请码表
type InvitationCode struct {
	ID pgtype.UUID `json:"id"`
	// 邀请码（6 位大写字母数字）
	Code      string             `json:"code"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	IsUsed    bool               `json:"is_used"`
	UsedBy    pgtype.UUID        `json:"used_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

// 对局表
type Match struct {
	ID pgtype.UUID `json:"id"`
	// 房间号（6 位字母数字）
	RoomCode string      `json:"room_code"`
	HostID   pgtype.UUID `json:"host_id"`
	// 对局状态：waiting, playing, finished
	Status      string      `json:"status"`
	PlayerCount int32       `json:"player_count"`
	AiCount     int32       `json:"ai_count"`
	WinnerID    pgtype.UUID `json:"winner_id"`
	// 胜利者类型：human 或 ai
	WinnerType *string `json:"winner_type"`
	// 总回合数
	TotalTurns int32 `json:"total_turns"`
	// 对局时长（秒）
	Duration   int32              `json:"duration"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	// 对局日志（JSON 格式存储关键事件）
	GameLog *string `json:"game_log"`
}

// 对局玩家关联表
type MatchPlayer struct {
	ID       pgtype.UUID `json:"id"`
	MatchID  pgtype.UUID `json:"match_id"`
	PlayerID pgtype.UUID `json:"player_id"`
	// 玩家编号（0-4）
	PlayerNumber int32 `json:"player_number"`
	IsHost       bool  `json:"is_host"`
	// 初始星系位置
	Position int32 `json:"position"`
	// 最终排名
	FinalRank    *int32 `json:"final_rank"`
	IsEliminated bool   `json:"is_eliminated"`
	// 被淘汰的回合
	EliminatedTurn *int32 `json:"eliminated_turn"`
	// 初始能量
	Energy int32 `json:"energy"`
	// 摧毁的恒星数
	DestroyedStars int32 `json:"destroyed_stars"`
	// 成功广播次数
	BroadcastCount int32 `json:"broadcast_count"`
	// 成功打击次数
	StrikeCount int32              `json:"strike_count"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// 匹配队列表
type MatchmakingQueue struct {
	ID       pgtype.UUID `json:"id"`
	PlayerID pgtype.UUID `json:"player_id"`
	// 期望玩家数（3-5）
	PreferredCount int32              `json:"preferred_count"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
	// 匹配超时（毫秒）
	Timeout int32 `json:"timeout"`
}

// 玩家表
type Player struct {
	ID pgtype.UUID `json:"id"`
	// 客户端生成的临时用户 ID
	UserID      string `json:"user_id"`
	DisplayName string `json:"display_name"`
	// 玩家角色：admin 或 player
	Role     string  `json:"role"`
	Password *string `json:"password"`
	// 头像 ID
	Avatar       int32              `json:"avatar"`
	Wins         int32              `json:"wins"`
	Losses       int32              `json:"losses"`
	Draws        int32              `json:"draws"`
	TotalMatches int32              `json:"total_matches"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// 文章表（预留）
type Post struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Content   *string            `json:"content"`
	Published bool               `json:"published"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// 回放表
type Replay struct {
	ID pgtype.UUID `json:"id"`
	// 关联的对局 ID
	MatchID pgtype.UUID `json:"match_id"`
	// 玩家 ID 列表（JSON 数组）
	PlayerIds string `json:"player_ids"`
	// 玩家名称列表（JSON 数组）
	PlayerNames string `json:"player_names"`
	// 动作序列（JSON 数组）
	Actions string `json:"actions"`
	// 最终游戏状态（JSON）
	FinalState *string            `json:"final_state"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// 用户表（预留，未来账号系统）
type User struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Name      *string            `json:"name"`
	Password  *string            `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
