// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type CustomMatchQueue struct {
	ID           string  `json:"id"`
	QueueID      string  `json:"queue_id"`
	QueueName    string  `json:"queue_name"`
	CreatorID    string  `json:"creator_id"`
	MaxPlayers   int64   `json:"max_players"`
	MinPlayers   int64   `json:"min_players"`
	Status       string  `json:"status"`
	BaseGameMode string  `json:"base_game_mode"`
	CustomRules  *string `json:"custom_rules"`
	MapID        *string `json:"map_id"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}

type CustomMatchQueuePlayer struct {
	ID       string `json:"id"`
	QueueID  string `json:"queue_id"`
	PlayerID string `json:"player_id"`
	JoinedAt string `json:"joined_at"`
	IsReady  bool   `json:"is_ready"`
}

type InvitationCode struct {
	ID        string  `json:"id"`
	Code      string  `json:"code"`
	CreatedBy string  `json:"created_by"`
	IsUsed    bool    `json:"is_used"`
	UsedBy    *string `json:"used_by"`
	CreatedAt string  `json:"created_at"`
	UsedAt    *string `json:"used_at"`
}

type Map struct {
	ID          string  `json:"id"`
	Slug        *string `json:"slug"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsOfficial  bool    `json:"is_official"`
	CreatedBy   *string `json:"created_by"`
	Version     int64   `json:"version"`
	LayoutJson  string  `json:"layout_json"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
}

type Match struct {
	ID          string  `json:"id"`
	RoomCode    string  `json:"room_code"`
	HostID      string  `json:"host_id"`
	Status      string  `json:"status"`
	PlayerCount int64   `json:"player_count"`
	AiCount     int64   `json:"ai_count"`
	WinnerID    *string `json:"winner_id"`
	WinnerType  *string `json:"winner_type"`
	TotalTurns  int64   `json:"total_turns"`
	Duration    int64   `json:"duration"`
	StartedAt   *string `json:"started_at"`
	FinishedAt  *string `json:"finished_at"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   string  `json:"updated_at"`
	GameLog     *string `json:"game_log"`
}

type MatchPlayer struct {
	ID             string `json:"id"`
	MatchID        string `json:"match_id"`
	PlayerID       string `json:"player_id"`
	PlayerNumber   int64  `json:"player_number"`
	IsHost         bool   `json:"is_host"`
	Position       int64  `json:"position"`
	FinalRank      *int64 `json:"final_rank"`
	IsEliminated   bool   `json:"is_eliminated"`
	EliminatedTurn *int64 `json:"eliminated_turn"`
	Energy         int64  `json:"energy"`
	DestroyedStars int64  `json:"destroyed_stars"`
	BroadcastCount int64  `json:"broadcast_count"`
	StrikeCount    int64  `json:"strike_count"`
	CreatedAt      string `json:"created_at"`
}

type MatchmakingQueue struct {
	ID             string `json:"id"`
	PlayerID       string `json:"player_id"`
	PreferredCount int64  `json:"preferred_count"`
	JoinedAt       string `json:"joined_at"`
	Timeout        int64  `json:"timeout"`
}

type Player struct {
	ID           string  `json:"id"`
	UserID       string  `json:"user_id"`
	DisplayName  string  `json:"display_name"`
	Role         string  `json:"role"`
	Password     *string `json:"password"`
	Avatar       int64   `json:"avatar"`
	Wins         int64   `json:"wins"`
	Losses       int64   `json:"losses"`
	Draws        int64   `json:"draws"`
	TotalMatches int64   `json:"total_matches"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}

type Post struct {
	ID        string  `json:"id"`
	Title     string  `json:"title"`
	Content   *string `json:"content"`
	Published bool    `json:"published"`
	AuthorID  string  `json:"author_id"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}

type Replay struct {
	ID           string  `json:"id"`
	MatchID      string  `json:"match_id"`
	PlayerIds    string  `json:"player_ids"`
	PlayerNames  string  `json:"player_names"`
	Actions      string  `json:"actions"`
	FinalState   *string `json:"final_state"`
	InitialState *string `json:"initial_state"`
	CreatedAt    string  `json:"created_at"`
}

type User struct {
	ID        string  `json:"id"`
	Email     string  `json:"email"`
	Name      *string `json:"name"`
	Password  *string `json:"password"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt string  `json:"updated_at"`
}
