// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayer = `-- name: CreatePlayer :one
INSERT INTO players (id, user_id, display_name, role, password, avatar, wins, losses, draws, total_matches)
VALUES ($1, $2, $3, $4, $5, $6, 0, 0, 0, 0)
RETURNING id, user_id, display_name, role, password, avatar, wins, losses, draws, total_matches, created_at, updated_at
`

type CreatePlayerParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      string      `json:"user_id"`
	DisplayName string      `json:"display_name"`
	Role        string      `json:"role"`
	Password    *string     `json:"password"`
	Avatar      int32       `json:"avatar"`
}

func (q *Queries) CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error) {
	row := q.db.QueryRow(ctx, createPlayer,
		arg.ID,
		arg.UserID,
		arg.DisplayName,
		arg.Role,
		arg.Password,
		arg.Avatar,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Role,
		&i.Password,
		&i.Avatar,
		&i.Wins,
		&i.Losses,
		&i.Draws,
		&i.TotalMatches,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlayer = `-- name: DeletePlayer :exec
DELETE FROM players
WHERE id = $1
`

func (q *Queries) DeletePlayer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlayer, id)
	return err
}

const getPlayerByDisplayName = `-- name: GetPlayerByDisplayName :one
SELECT id, user_id, display_name, role, password, avatar, wins, losses, draws, total_matches, created_at, updated_at
FROM players
WHERE display_name = $1 LIMIT 1
`

func (q *Queries) GetPlayerByDisplayName(ctx context.Context, displayName string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByDisplayName, displayName)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Role,
		&i.Password,
		&i.Avatar,
		&i.Wins,
		&i.Losses,
		&i.Draws,
		&i.TotalMatches,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, user_id, display_name, role, password, avatar, wins, losses, draws, total_matches, created_at, updated_at
FROM players
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id pgtype.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Role,
		&i.Password,
		&i.Avatar,
		&i.Wins,
		&i.Losses,
		&i.Draws,
		&i.TotalMatches,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerByRole = `-- name: GetPlayerByRole :one
SELECT id, user_id, display_name, role, password, avatar, wins, losses, draws, total_matches, created_at, updated_at
FROM players
WHERE role = $1
LIMIT 1
`

func (q *Queries) GetPlayerByRole(ctx context.Context, role string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByRole, role)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Role,
		&i.Password,
		&i.Avatar,
		&i.Wins,
		&i.Losses,
		&i.Draws,
		&i.TotalMatches,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayerByUserID = `-- name: GetPlayerByUserID :one
SELECT id, user_id, display_name, role, password, avatar, wins, losses, draws, total_matches, created_at, updated_at
FROM players
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetPlayerByUserID(ctx context.Context, userID string) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByUserID, userID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Role,
		&i.Password,
		&i.Avatar,
		&i.Wins,
		&i.Losses,
		&i.Draws,
		&i.TotalMatches,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlayers = `-- name: ListPlayers :many
SELECT id, user_id, display_name, role, avatar, wins, losses, draws, total_matches, created_at, updated_at
FROM players
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPlayersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPlayersRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       string             `json:"user_id"`
	DisplayName  string             `json:"display_name"`
	Role         string             `json:"role"`
	Avatar       int32              `json:"avatar"`
	Wins         int32              `json:"wins"`
	Losses       int32              `json:"losses"`
	Draws        int32              `json:"draws"`
	TotalMatches int32              `json:"total_matches"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPlayers(ctx context.Context, arg ListPlayersParams) ([]ListPlayersRow, error) {
	rows, err := q.db.Query(ctx, listPlayers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayersRow{}
	for rows.Next() {
		var i ListPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Role,
			&i.Avatar,
			&i.Wins,
			&i.Losses,
			&i.Draws,
			&i.TotalMatches,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayerPassword = `-- name: UpdatePlayerPassword :one
UPDATE players
SET password = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, updated_at
`

type UpdatePlayerPasswordParams struct {
	ID       pgtype.UUID `json:"id"`
	Password *string     `json:"password"`
}

type UpdatePlayerPasswordRow struct {
	ID        pgtype.UUID        `json:"id"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePlayerPassword(ctx context.Context, arg UpdatePlayerPasswordParams) (UpdatePlayerPasswordRow, error) {
	row := q.db.QueryRow(ctx, updatePlayerPassword, arg.ID, arg.Password)
	var i UpdatePlayerPasswordRow
	err := row.Scan(&i.ID, &i.UpdatedAt)
	return i, err
}

const updatePlayerStats = `-- name: UpdatePlayerStats :one
UPDATE players
SET wins = $2, losses = $3, draws = $4, total_matches = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, wins, losses, draws, total_matches, updated_at
`

type UpdatePlayerStatsParams struct {
	ID           pgtype.UUID `json:"id"`
	Wins         int32       `json:"wins"`
	Losses       int32       `json:"losses"`
	Draws        int32       `json:"draws"`
	TotalMatches int32       `json:"total_matches"`
}

type UpdatePlayerStatsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Wins         int32              `json:"wins"`
	Losses       int32              `json:"losses"`
	Draws        int32              `json:"draws"`
	TotalMatches int32              `json:"total_matches"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdatePlayerStats(ctx context.Context, arg UpdatePlayerStatsParams) (UpdatePlayerStatsRow, error) {
	row := q.db.QueryRow(ctx, updatePlayerStats,
		arg.ID,
		arg.Wins,
		arg.Losses,
		arg.Draws,
		arg.TotalMatches,
	)
	var i UpdatePlayerStatsRow
	err := row.Scan(
		&i.ID,
		&i.Wins,
		&i.Losses,
		&i.Draws,
		&i.TotalMatches,
		&i.UpdatedAt,
	)
	return i, err
}
