// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddPlayerToMatch(ctx context.Context, arg AddPlayerToMatchParams) (AddPlayerToMatchRow, error)
	ClearMatchmakingQueue(ctx context.Context, dollar_1 []pgtype.UUID) error
	CountPlayersInMatch(ctx context.Context, matchID pgtype.UUID) (int64, error)
	CountPlayersInQueue(ctx context.Context, preferredCount int32) (int64, error)
	CreateInvitationCode(ctx context.Context, arg CreateInvitationCodeParams) (InvitationCode, error)
	CreateMatch(ctx context.Context, arg CreateMatchParams) (CreateMatchRow, error)
	CreatePlayer(ctx context.Context, arg CreatePlayerParams) (Player, error)
	CreateReplay(ctx context.Context, arg CreateReplayParams) (Replay, error)
	DeleteInvitationCode(ctx context.Context, id pgtype.UUID) error
	DeleteMatch(ctx context.Context, id pgtype.UUID) error
	DeletePlayer(ctx context.Context, id pgtype.UUID) error
	DeleteReplay(ctx context.Context, id pgtype.UUID) error
	DeleteReplaysByMatchID(ctx context.Context, matchID pgtype.UUID) error
	FinishMatch(ctx context.Context, arg FinishMatchParams) (FinishMatchRow, error)
	GetAllQueues(ctx context.Context) ([]MatchmakingQueue, error)
	GetInvitationCode(ctx context.Context, code string) (InvitationCode, error)
	GetMatchByID(ctx context.Context, id pgtype.UUID) (GetMatchByIDRow, error)
	GetMatchByRoomCode(ctx context.Context, roomCode string) (GetMatchByRoomCodeRow, error)
	GetMatchPlayer(ctx context.Context, arg GetMatchPlayerParams) (MatchPlayer, error)
	GetPlayerByDisplayName(ctx context.Context, displayName string) (Player, error)
	GetPlayerByID(ctx context.Context, id pgtype.UUID) (Player, error)
	GetPlayerByRole(ctx context.Context, role string) (Player, error)
	GetPlayerByUserID(ctx context.Context, userID string) (Player, error)
	GetPlayerInQueue(ctx context.Context, playerID pgtype.UUID) (MatchmakingQueue, error)
	GetPlayersInQueue(ctx context.Context, arg GetPlayersInQueueParams) ([]MatchmakingQueue, error)
	GetReplayByID(ctx context.Context, id pgtype.UUID) (Replay, error)
	GetReplayByMatchID(ctx context.Context, matchID pgtype.UUID) (Replay, error)
	JoinMatchmakingQueue(ctx context.Context, arg JoinMatchmakingQueueParams) (MatchmakingQueue, error)
	LeaveMatchmakingQueue(ctx context.Context, playerID pgtype.UUID) error
	ListInvitationCodesByCreator(ctx context.Context, createdBy pgtype.UUID) ([]InvitationCode, error)
	ListMatches(ctx context.Context, arg ListMatchesParams) ([]ListMatchesRow, error)
	ListMatchesByPlayer(ctx context.Context, arg ListMatchesByPlayerParams) ([]ListMatchesByPlayerRow, error)
	ListPlayers(ctx context.Context, arg ListPlayersParams) ([]ListPlayersRow, error)
	ListPlayersByMatch(ctx context.Context, matchID pgtype.UUID) ([]MatchPlayer, error)
	ListReplays(ctx context.Context, arg ListReplaysParams) ([]Replay, error)
	ListReplaysByPlayer(ctx context.Context, arg ListReplaysByPlayerParams) ([]Replay, error)
	RemovePlayerFromMatch(ctx context.Context, arg RemovePlayerFromMatchParams) error
	StartMatch(ctx context.Context, id pgtype.UUID) (StartMatchRow, error)
	UpdateMatchPlayerStats(ctx context.Context, arg UpdateMatchPlayerStatsParams) (UpdateMatchPlayerStatsRow, error)
	UpdatePlayerPassword(ctx context.Context, arg UpdatePlayerPasswordParams) (UpdatePlayerPasswordRow, error)
	UpdatePlayerStats(ctx context.Context, arg UpdatePlayerStatsParams) (UpdatePlayerStatsRow, error)
	UseInvitationCode(ctx context.Context, arg UseInvitationCodeParams) (InvitationCode, error)
}

var _ Querier = (*Queries)(nil)
