// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replays.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReplay = `-- name: CreateReplay :one
INSERT INTO replays (id, match_id, player_ids, player_names, actions, final_state)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, match_id, player_ids, player_names, actions, final_state, created_at
`

type CreateReplayParams struct {
	ID          pgtype.UUID `json:"id"`
	MatchID     pgtype.UUID `json:"match_id"`
	PlayerIds   string      `json:"player_ids"`
	PlayerNames string      `json:"player_names"`
	Actions     string      `json:"actions"`
	FinalState  *string     `json:"final_state"`
}

func (q *Queries) CreateReplay(ctx context.Context, arg CreateReplayParams) (Replay, error) {
	row := q.db.QueryRow(ctx, createReplay,
		arg.ID,
		arg.MatchID,
		arg.PlayerIds,
		arg.PlayerNames,
		arg.Actions,
		arg.FinalState,
	)
	var i Replay
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerIds,
		&i.PlayerNames,
		&i.Actions,
		&i.FinalState,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReplay = `-- name: DeleteReplay :exec
DELETE FROM replays
WHERE id = $1
`

func (q *Queries) DeleteReplay(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReplay, id)
	return err
}

const deleteReplaysByMatchID = `-- name: DeleteReplaysByMatchID :exec
DELETE FROM replays
WHERE match_id = $1
`

func (q *Queries) DeleteReplaysByMatchID(ctx context.Context, matchID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReplaysByMatchID, matchID)
	return err
}

const getReplayByID = `-- name: GetReplayByID :one
SELECT id, match_id, player_ids, player_names, actions, final_state, created_at
FROM replays
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReplayByID(ctx context.Context, id pgtype.UUID) (Replay, error) {
	row := q.db.QueryRow(ctx, getReplayByID, id)
	var i Replay
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerIds,
		&i.PlayerNames,
		&i.Actions,
		&i.FinalState,
		&i.CreatedAt,
	)
	return i, err
}

const getReplayByMatchID = `-- name: GetReplayByMatchID :one
SELECT id, match_id, player_ids, player_names, actions, final_state, created_at
FROM replays
WHERE match_id = $1 LIMIT 1
`

func (q *Queries) GetReplayByMatchID(ctx context.Context, matchID pgtype.UUID) (Replay, error) {
	row := q.db.QueryRow(ctx, getReplayByMatchID, matchID)
	var i Replay
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerIds,
		&i.PlayerNames,
		&i.Actions,
		&i.FinalState,
		&i.CreatedAt,
	)
	return i, err
}

const listReplays = `-- name: ListReplays :many
SELECT id, match_id, player_ids, player_names, actions, final_state, created_at
FROM replays
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListReplaysParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListReplays(ctx context.Context, arg ListReplaysParams) ([]Replay, error) {
	rows, err := q.db.Query(ctx, listReplays, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Replay{}
	for rows.Next() {
		var i Replay
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerIds,
			&i.PlayerNames,
			&i.Actions,
			&i.FinalState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplaysByPlayer = `-- name: ListReplaysByPlayer :many
SELECT r.id, r.match_id, r.player_ids, r.player_names, r.actions, r.final_state, r.created_at
FROM replays r
JOIN match_players mp ON r.match_id = mp.match_id
WHERE mp.player_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListReplaysByPlayerParams struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListReplaysByPlayer(ctx context.Context, arg ListReplaysByPlayerParams) ([]Replay, error) {
	rows, err := q.db.Query(ctx, listReplaysByPlayer, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Replay{}
	for rows.Next() {
		var i Replay
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerIds,
			&i.PlayerNames,
			&i.Actions,
			&i.FinalState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
