// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: replays.sql

package db

import (
	"context"
)

const createReplay = `-- name: CreateReplay :one
INSERT INTO replays (id, match_id, player_ids, player_names, actions, initial_state, final_state)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, match_id, player_ids, player_names, actions, initial_state, final_state, created_at
`

type CreateReplayParams struct {
	ID           string  `json:"id"`
	MatchID      string  `json:"match_id"`
	PlayerIds    string  `json:"player_ids"`
	PlayerNames  string  `json:"player_names"`
	Actions      string  `json:"actions"`
	InitialState *string `json:"initial_state"`
	FinalState   *string `json:"final_state"`
}

type CreateReplayRow struct {
	ID           string  `json:"id"`
	MatchID      string  `json:"match_id"`
	PlayerIds    string  `json:"player_ids"`
	PlayerNames  string  `json:"player_names"`
	Actions      string  `json:"actions"`
	InitialState *string `json:"initial_state"`
	FinalState   *string `json:"final_state"`
	CreatedAt    string  `json:"created_at"`
}

func (q *Queries) CreateReplay(ctx context.Context, arg CreateReplayParams) (CreateReplayRow, error) {
	row := q.db.QueryRowContext(ctx, createReplay,
		arg.ID,
		arg.MatchID,
		arg.PlayerIds,
		arg.PlayerNames,
		arg.Actions,
		arg.InitialState,
		arg.FinalState,
	)
	var i CreateReplayRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerIds,
		&i.PlayerNames,
		&i.Actions,
		&i.InitialState,
		&i.FinalState,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReplay = `-- name: DeleteReplay :exec
DELETE FROM replays
WHERE id = ?1
`

func (q *Queries) DeleteReplay(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteReplay, id)
	return err
}

const deleteReplaysByMatchID = `-- name: DeleteReplaysByMatchID :exec
DELETE FROM replays
WHERE match_id = ?1
`

func (q *Queries) DeleteReplaysByMatchID(ctx context.Context, matchID string) error {
	_, err := q.db.ExecContext(ctx, deleteReplaysByMatchID, matchID)
	return err
}

const getReplayByID = `-- name: GetReplayByID :one
SELECT id, match_id, player_ids, player_names, actions, initial_state, final_state, created_at
FROM replays
WHERE id = ?1 LIMIT 1
`

type GetReplayByIDRow struct {
	ID           string  `json:"id"`
	MatchID      string  `json:"match_id"`
	PlayerIds    string  `json:"player_ids"`
	PlayerNames  string  `json:"player_names"`
	Actions      string  `json:"actions"`
	InitialState *string `json:"initial_state"`
	FinalState   *string `json:"final_state"`
	CreatedAt    string  `json:"created_at"`
}

func (q *Queries) GetReplayByID(ctx context.Context, id string) (GetReplayByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReplayByID, id)
	var i GetReplayByIDRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerIds,
		&i.PlayerNames,
		&i.Actions,
		&i.InitialState,
		&i.FinalState,
		&i.CreatedAt,
	)
	return i, err
}

const getReplayByMatchID = `-- name: GetReplayByMatchID :one
SELECT id, match_id, player_ids, player_names, actions, initial_state, final_state, created_at
FROM replays
WHERE match_id = ?1 LIMIT 1
`

type GetReplayByMatchIDRow struct {
	ID           string  `json:"id"`
	MatchID      string  `json:"match_id"`
	PlayerIds    string  `json:"player_ids"`
	PlayerNames  string  `json:"player_names"`
	Actions      string  `json:"actions"`
	InitialState *string `json:"initial_state"`
	FinalState   *string `json:"final_state"`
	CreatedAt    string  `json:"created_at"`
}

func (q *Queries) GetReplayByMatchID(ctx context.Context, matchID string) (GetReplayByMatchIDRow, error) {
	row := q.db.QueryRowContext(ctx, getReplayByMatchID, matchID)
	var i GetReplayByMatchIDRow
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.PlayerIds,
		&i.PlayerNames,
		&i.Actions,
		&i.InitialState,
		&i.FinalState,
		&i.CreatedAt,
	)
	return i, err
}

const listReplaySummariesByPlayer = `-- name: ListReplaySummariesByPlayer :many
SELECT r.id, r.match_id, r.player_ids, r.player_names, r.final_state, r.created_at
FROM replays r
JOIN match_players mp ON r.match_id = mp.match_id
WHERE mp.player_id = ?1
ORDER BY r.created_at DESC
LIMIT ?2 OFFSET ?3
`

type ListReplaySummariesByPlayerParams struct {
	PlayerID string `json:"player_id"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

type ListReplaySummariesByPlayerRow struct {
	ID          string  `json:"id"`
	MatchID     string  `json:"match_id"`
	PlayerIds   string  `json:"player_ids"`
	PlayerNames string  `json:"player_names"`
	FinalState  *string `json:"final_state"`
	CreatedAt   string  `json:"created_at"`
}

// List view: summary fields + final_state only (for deriving winner/totalTurns),
// skipping the two large fields actions and initial_state to avoid needless deserialization.
func (q *Queries) ListReplaySummariesByPlayer(ctx context.Context, arg ListReplaySummariesByPlayerParams) ([]ListReplaySummariesByPlayerRow, error) {
	rows, err := q.db.QueryContext(ctx, listReplaySummariesByPlayer, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReplaySummariesByPlayerRow{}
	for rows.Next() {
		var i ListReplaySummariesByPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerIds,
			&i.PlayerNames,
			&i.FinalState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplays = `-- name: ListReplays :many
SELECT id, match_id, player_ids, player_names, actions, initial_state, final_state, created_at
FROM replays
ORDER BY created_at DESC
LIMIT ?1 OFFSET ?2
`

type ListReplaysParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

type ListReplaysRow struct {
	ID           string  `json:"id"`
	MatchID      string  `json:"match_id"`
	PlayerIds    string  `json:"player_ids"`
	PlayerNames  string  `json:"player_names"`
	Actions      string  `json:"actions"`
	InitialState *string `json:"initial_state"`
	FinalState   *string `json:"final_state"`
	CreatedAt    string  `json:"created_at"`
}

func (q *Queries) ListReplays(ctx context.Context, arg ListReplaysParams) ([]ListReplaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listReplays, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReplaysRow{}
	for rows.Next() {
		var i ListReplaysRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerIds,
			&i.PlayerNames,
			&i.Actions,
			&i.InitialState,
			&i.FinalState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplaysByPlayer = `-- name: ListReplaysByPlayer :many
SELECT r.id, r.match_id, r.player_ids, r.player_names, r.actions, r.initial_state, r.final_state, r.created_at
FROM replays r
JOIN match_players mp ON r.match_id = mp.match_id
WHERE mp.player_id = ?1
ORDER BY r.created_at DESC
LIMIT ?2 OFFSET ?3
`

type ListReplaysByPlayerParams struct {
	PlayerID string `json:"player_id"`
	Limit    int64  `json:"limit"`
	Offset   int64  `json:"offset"`
}

type ListReplaysByPlayerRow struct {
	ID           string  `json:"id"`
	MatchID      string  `json:"match_id"`
	PlayerIds    string  `json:"player_ids"`
	PlayerNames  string  `json:"player_names"`
	Actions      string  `json:"actions"`
	InitialState *string `json:"initial_state"`
	FinalState   *string `json:"final_state"`
	CreatedAt    string  `json:"created_at"`
}

func (q *Queries) ListReplaysByPlayer(ctx context.Context, arg ListReplaysByPlayerParams) ([]ListReplaysByPlayerRow, error) {
	rows, err := q.db.QueryContext(ctx, listReplaysByPlayer, arg.PlayerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReplaysByPlayerRow{}
	for rows.Next() {
		var i ListReplaysByPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.PlayerIds,
			&i.PlayerNames,
			&i.Actions,
			&i.InitialState,
			&i.FinalState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
